### ISSUE TITLE
Phinx.yml compatibility

### ISSUE THREAD

**Issue by jonneroelofs** [odan/phinx-migrations-generator#10]
Hi,

We like to keep our db connection info, and therefore the phinx.yml, outside of our web root folder and the db/migrations inside the web folder. For example:

-private
--phinx.yml
-web
--db
---migrations

I got this to work for Phinx with a wildcard like below. We use the wildcard because the name of the webfolder is unfortunately different in development and production. 

paths:
    migrations: ../*/db/migrations

However it seems to break the phinx-migrations-generator.
![image](https://cloud.githubusercontent.com/assets/20800818/25218550/78678ee6-25ab-11e7-822e-fabb6b96f67e.png)

Cheers,

Jonne

**Comment by odan** [comment]
Hi Jonne

You should place only public assets like JavaScript, CSS and images into the web folder. For security reason migrations files should not be placed in a public folder.

However, the path `../*/db/migrations` with the `*` is not a valid path for this tool.
Please try (a non public) path without a the `*` wildcard.  
For example: `../resources/migrations`

**Comment by jonneroelofs** [comment]
Fair point. I'll move the folder. Thanks.
