### ISSUE TITLE
[MariaDB] Setting NULL as default value is ignored

### ISSUE THREAD

**Issue by bkrnetic** [odan/phinx-migrations-generator#105]
Hello,

I use MariaDB 10.3.31 version and migration ignores `null` as default value.

I use it this way:

```
$table->addColumn('foo', 'string', ['null' => true, 'default' => NULL])
```

It doesn't work for timestamp fields either...

Are you familiar with this issue? Is it maybe something related to MariaDB?

To me it seems like a basic feature. 🤷‍♂️  Hopefully somebody can help me out!

Best regards,
Bruno

**Comment by odan** [comment]
Is your code example part of the generated PHP code?
Did you run this code and phinx did not create a column with null? If yes, it could be related to phinx itself.

**Comment by bkrnetic** [comment]
Damn I completely mixed up repositories 🤦‍♂️. I should have posted it to https://github.com/cakephp/phinx/issues 

Please ignore this and close the issue!
