### ISSUE TITLE
PostgreSQL Adapter

### ISSUE THREAD

**Issue by LudwigBr** [odan/phinx-migrations-generator#11]
Hello,

are you planning to support PostgreSQL?
If not it seems like I would only need to implement another Adapter class beside the MySqlAdapter.php am I right or is there some other "mysql-only" logic in your script?

Best Regards

**Comment by odan** [comment]
Hello,

MySQL is the only supported database system. 
To be honest, PostgreSQL is not planned for the future.

**Comment by guilhermeaiolfi** [comment]
@LudwigBr have you done any further in this?

**Comment by LudwigBr** [comment]
@guilhermeaiolfi Sorry for my late answer. I have not pushed this further and instead went for a new implementation. It fit my needs back then but was not intended for public use. In case you want to take a look anyway: https://github.com/LudwigBr/postgres-migration
