### ISSUE TITLE
Invalid default value for datetime column 

### ISSUE THREAD

**Issue by samuelgfeller** [odan/phinx-migrations-generator#111]
I have a table with a `DATETIME` column whose default value is `current_timestamp()`. 

The generator creates this from my database: 
```php
$this->table('table_name', [/* ... */])
->addColumn('updated_at', 'datetime', [
    'null' => false,
    'default' => 'current_timestamp()',
    'after' => 'hidden',
])
``` 
When running the migration, I get this error: 
```
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'updated_at'
```
And I the SQL provided with the error is the following ([full result](https://github.com/samuelgfeller/slim-example-project/actions/runs/3855920365/jobs/6571511623)): 
```
CREATE TABLE `note`
(
    --  ... other columns
    `updated_at` DATETIME NOT NULL DEFAULT 'current_timestamp()',
)
-- ... engine, charset etc.
;
```
The issue are the single quotes around the default function `current_timestamp()`.

Did I do something wrong; can I fix the issue? 

Happens on the remote server and locally. 
Server version: 10.3.37-MariaDB

**Comment by odan** [comment]
Have you tried to use `CURRENT_TIMESTAMP` as default instead?

**Comment by odan** [comment]
It should be fixed now in the latest version. Please try it and give me a feedback. Thanks.

**Comment by samuelgfeller** [comment]
I deleted the previously generated migrations and regenerated one, dropped all tables, ran the migration and it worked! 

Thanks for the fix.
