### ISSUE TITLE
fix dependency issue

### ISSUE THREAD

**Issue by demmmmios** [odan/phinx-migrations-generator#113]
Tag 2.0.x was deleted. Please revert dependency is this package :)

https://github.com/cakephp/phinx/releases/tag/0.15.0

**Comment by odan** [comment]
Should be fixed now.

**Comment by demmmmios** [comment]
thanks, but now, it is not compatible with latest phinx 0.15 :(

**Comment by odan** [comment]
Yes I know, there are suddenly some issues with 0.15, that I try to fix now.

**Comment by odan** [comment]
This should also be fixed now in the latest version.
