### ISSUE TITLE
Dependcy issues

### ISSUE THREAD

**Issue by 24unix** [odan/phinx-migrations-generator#117]
Hi, I'm trying to learn Phinx, as on my job we use Cake (erm, Cake 2 … no migration strategy at all, but we are finally willing to upgrade.)
I'm used to work with Symfony and Doctrine, so phinx-migration-generator seems to be the missing part to make my live happy in the Cake world.

For a private project I wanted to test the migration-generator, but it was moaning about my composer.json requiring Phinx 0.16.0 and symfony/console 7.06, no big deal, as my project is not Symfony based, I can downgrade both packages, but maybe an upgrade makes sense? Symfony 7 is out for  a while now and has no breaking changes against 6.4.

**Comment by odan** [comment]
Thanks for reporting. This should be fixed now in the latest version.

https://github.com/odan/phinx-migrations-generator/releases/tag/6.2.0
