### ISSUE TITLE
named identifiers

### ISSUE THREAD

**Issue by 24unix** [odan/phinx-migrations-generator#118]
This is not really an issue, more a specific preference.

I really like named identifiers, but the generator doesn't agree with me :-)

<img width="1042" alt="image" src="https://github.com/odan/phinx-migrations-generator/assets/36622631/06a0ec63-b4cd-4bee-bcf6-21959ff891c9">

As it has no impact on the behavior I agree that this is a really minor thing, but would you accept a PR which adds named identifiers to the generated migrations?

If yes, please be patient with me, I never did a PR on GitHub (for reasons …), at work we use GitLab and I personally use Gitea.

**Comment by odan** [comment]
Hi @24unix I'm not a fan of named arguments and try to avoid them. Most IDEs already support type hinting for parameters, so everyone can configure it to their own taste. So I would not merge such a PR.

**Comment by 24unix** [comment]
Fair enough :-) 
Glad that I asked before …

**Comment by 24unix** [comment]
Hi @odan, sorry to bother you again, but I couldn't find sleep this night :-)
I don't want to reopen this issue, just to clarify:
I meant named arguments, not type hinting, sorry, was not concentrated when I replied to your post. 
It's not about
```public function foo(int $a, string $b, array $c) {}```
vs
```public function foo($a, $b, $c) {}```
but about
```foo(null, null, ['foo', 'bar']);```
vs
```foo(c: ['foo', 'bar']);```
You notice the difference?

**Comment by odan** [comment]
Indeed, I'm well aware of the distinction.  :-)

I understand that this IDE functionality is unrelated to PHP's "named identifiers" syntax. 

While I initially mentioned "named arguments," I later referred to "type hinting for parameters." My apologies for any confusion. Essentially, what I meant to convey is that most IDEs already provide visibility into the parameter names being passed. In PHPStorm, for instance, this feature is termed "Show name of all parameters," previously known as "Show parameter hints" in older versions. That was the more accurate term I intended to highlight.

![image](https://github.com/odan/phinx-migrations-generator/assets/781074/6ea4c8b9-ba04-4fba-8035-b8e773b8b12f)

![image](https://github.com/odan/phinx-migrations-generator/assets/781074/3c885628-a186-4324-8489-c5cf0056032a)

Regarding named arguments, I personally tend to avoid them. My point was simply that they're not necessary.

**Comment by 24unix** [comment]
I personally use PHPStorm, too. I'm aware of the feature.
The point is, with named argument you can omit unneeded parameters, which is IMHO a great feature.
However that is just a question of personal preferences.
Anyways, thanks for  the great software, for me it is vital to make real use of Phinx.
