### ISSUE TITLE
Renaming a column replaces it with a new one

### ISSUE THREAD

**Issue by samuelgfeller** [odan/phinx-migrations-generator#120]
Hi Daniel

I renamed a column locally, generated a migration and this is in the migration file: 

```php
<?php

use Phinx\Db\Adapter\MysqlAdapter;

class DbChange160867212671a2f06cfbf3 extends Phinx\Migration\AbstractMigration
{
    public function change()
    {
        $this->table('table_name', [
                'id' => false,
                'primary_key' => ['id'],
                'engine' => 'InnoDB',
                'encoding' => 'utf8mb4',
                'collation' => 'utf8mb4_general_ci',
                'comment' => '',
                'row_format' => 'DYNAMIC',
            ])
            ->addColumn('new_column_name', 'string', [
                'null' => true,
                'default' => null,
                'limit' => 300,
                'collation' => 'utf8mb4_general_ci',
                'encoding' => 'utf8mb4',
                'after' => 'previous_column',
            ])
            ->removeColumn('old_column_name')
            ->save();
    }
}
```
Instead of renaming the column, it deletes the column with the old name and adds a new one. 

Maybe this is the intended behavior because I can imagine it's hard to catch a column rename but it leads to the loss of all the data saved under the old column's name which is far from ideal.

**Comment by odan** [comment]
Hi @samuelgfeller This is a known behavior (or limitation) because of the diff in the old and the new schema. 
If you rename a column, then you could replace this generated method manually with an "up" method like this:

```php
public function up()
{
    $table = $this->table('table_name');
    $table->renameColumn('old_column_name', 'new_column_name');
}
```

See here: https://netlor-phinx.readthedocs.io/en/stable/migrations.html#renaming-a-column

**Comment by samuelgfeller** [comment]
So in the migration file, after the `change` method i make another `up` method use the code you provided? 

Or could I also replace this part in the `change` function:

```php
// ...
            ->addColumn('new_column_name', 'string', [
                'null' => true,
                'default' => null,
                'limit' => 300,
                'collation' => 'utf8mb4_general_ci',
                'encoding' => 'utf8mb4',
                'after' => 'previous_column',
            ])
            ->removeColumn('old_column_name')
// ...
```
with this:
```php
->renameColumn('old_column_name', 'new_column_name');
```

That would be the easiest solution if it works.

**Comment by odan** [comment]
As far as I know it would not work having a "up" and a "change" method in the same migration class. It's up to you. Use either the one or the other, but not both.

**Comment by samuelgfeller** [comment]
I'll try `->renameColumn('old_column_name', 'new_column_name');` in the `change()` method as this is the one that is generated by your library. If that works it's a fairly easy fix. Thanks for the help.

**Comment by samuelgfeller** [comment]
This bit me in the butt again. Really unexpected because everything else works so seamlessly!
It's so crucial to have that in mind constantly because that can do some real damage if pushed to a productive system. 

I hope I will find the time to make a PR that displays a clear warning in the console when columns are removed and added, shown right after the generation. I think this would help me and maybe others to pay attention to that (and potentially save the day big time :). Do you think it's a good idea?

Of course I'm happy if you want to do it.

**Comment by odan** [comment]
> displays a clear warning in the console when columns are removed and added

That would be possible, but I would strongly recommend always manually reviewing and testing the generated migration class in a staging environment before deploying it to production.

What I / we could do is to add a warning in generated output when the tool detects a suspicious pattern like:

- one column removed
- one column added
- same table
- same type / limit / nullability / default
- That warning could say: "Possible column rename detected. Please review manually and consider using renameColumn() to preserve data."

**Comment by samuelgfeller** [comment]
Yes! exactly what I had in mind. I would not limit it to one column added/removed though, when I'm working on a feature, it can happen that I rename more than one column and do other changes to other columns of the same table in one migration.

But this can still be tested with a bit looser rules for instance by checking that at least 1 column was added and one removed and in the removed / added columns there is at least 1 match that has same type / limit / nullability / default
