### ISSUE TITLE
Call to undefined method Phinx\Db\Adapter\TablePrefixAdapter::getConnection()

### ISSUE THREAD

**Issue by qopqopqop** [odan/phinx-migrations-generator#13]
Adding table_prefix: xxx_  to phinx.yml throws exception below.

PHP Fatal error:  Call to undefined method Phinx\Db\Adapter\TablePrefixAdapter::getConnection() in /home/ubuntu/workspace/vendor/odan/phinx-migrations-generator/src/Migration/Command/GenerateCommand.php on line 95

cheers

**Comment by odan** [comment]
Hi! This should be fixed now.
