### ISSUE TITLE
changeColumn error

### ISSUE THREAD

**Issue by aat2703** [odan/phinx-migrations-generator#14]
Version: 0.8.0

I just created a new column named 'number' but the addColumn() method is missing ->update() and therefor this statement fails:
$this->table("restaurant_orderLinkCustomers")->changeColumn('zipcode', 'string', ['null' => true, 'default' => '', 'limit' => 8, 'collation' => "latin1_swedish_ci", 'encoding' => "latin1", 'after' => 'number'])->update();

because the field is 'number' not yet created and cannot be set after the column 'number'

file: 20170526115828_test1.php
```
class Test1 extends AbstractMigration
{
    public function change()
    {
        $table = $this->table("restaurant_orderLinkCustomers");
        $table->addColumn('number', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'company']);
        $this->table("restaurant_orderLinkCustomers")->changeColumn('zipcode', 'string', ['null' => true, 'default' => '', 'limit' => 8, 'collation' => "latin1_swedish_ci", 'encoding' => "latin1", 'after' => 'number'])->update();
        $this->table("restaurant_orderLinkCustomers")->changeColumn('address', 'string', ['null' => true, 'default' => '', 'limit' => 128, 'collation' => "latin1_swedish_ci", 'encoding' => "latin1", 'after' => 'zipcode'])->update();
        $this->table("restaurant_orderLinkCustomers")->changeColumn('phoneNumber', 'string', ['null' => true, 'default' => '', 'limit' => 25, 'collation' => "latin1_swedish_ci", 'encoding' => "latin1", 'after' => 'address'])->update();
        $this->table("restaurant_orderLinkCustomers")->changeColumn('arrival', 'string', ['null' => true, 'default' => '', 'limit' => 124, 'collation' => "latin1_swedish_ci", 'encoding' => "latin1", 'after' => 'phoneNumber'])->update();
        $this->table("restaurant_orderLinkCustomers")->changeColumn('resellerChainID', 'integer', ['null' => true, 'default' => '0', 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'arrival'])->update();
        $this->table("restaurant_orderLinkCustomers")->changeColumn('createTime', 'timestamp', ['null' => true, 'default' => 'CURRENT_TIMESTAMP', 'after' => 'resellerChainID'])->update();
        $table->save();
    }
}
```

`Error:   [PDOException]                                                                                      
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'number' in 'restaurant_orderlinkcustomers' `

**Comment by odan** [comment]
Hi! Is it possible for you to update to to latest version?

**Comment by aat2703** [comment]
Hi

Isn't the version v0.8.0 on Composer the latest version :-) ?

Sendt fra min iPhone

Den 26. maj 2017 kl. 17.47 skrev Daniel Opitz <notifications@github.com<mailto:notifications@github.com>>:


Hi! Is it possible for you to update to to latest version?

**Comment by odan** [comment]
The current version is 2.1.1. Please take a look at the [Releases page](https://github.com/odan/phinx-migrations-generator/releases) or just run `composer update`.

**Comment by aat2703** [comment]
Wops, i'm already on version 2.1.1 who has the problem

________________________________
Fra: Daniel Opitz <notifications@github.com>
Sendt: 26. maj 2017 21:15:46
Til: odan/phinx-migrations-generator
Cc: Andreas Aagaard; Author
Emne: Re: [odan/phinx-migrations-generator] changeColumn error (#14)


The current version is 2.1.1. Please take a look at the Releases page<https://github.com/odan/phinx-migrations-generator/releases> or just run composer update.

**Comment by odan** [comment]
Should be fixed. Please run `composer update` and try it again.
