### ISSUE TITLE
Cannot create table when table has custom PK

### ISSUE THREAD

**Issue by kaoz70** [odan/phinx-migrations-generator#16]
I'm getting a:

    [RuntimeException]                              
    Cannot update a table that doesn't exist!

With this generated code:

    $table = $this->table("role_sections", ['id' => false, 'primary_key' => ["role_id", "section_name"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => ""]);
    $table->addColumn('role_id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'signed' => false])->update();;
    $table->addColumn('section_name', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'role_id'])->update();;
    $table->save();

As you can see this table doe not have an "id" column, but 2 PK columns, the resulting generated code should be like this (no ->update(); at the end of each column):

    $table = $this->table("role_sections", ['id' => false, 'primary_key' => ["role_id", "section_name"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => ""]);
    $table->addColumn('role_id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'signed' => false]);
    $table->addColumn('section_name', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'role_id']);
    $table->save();

**Comment by odan** [comment]
Should be fixed now. Please run composer update and try it again.

**Comment by kaoz70** [comment]
Yep, its fixed now, no problems in the migration. Thanks!!
