### ISSUE TITLE
Problem with alternative primary key

### ISSUE THREAD

**Issue by claytonrcarter** [odan/phinx-migrations-generator#19]
I have the following migration generated by v2.1.4, from a MySQL database:

```php
$table = $this->table("bulbs_orders", ['id' => false, 'primary_key' => ["line"], 'engine' => "MyISAM", 'encoding' => "latin1", 'collation' => "latin1_swedish_ci", 'comment' => "bulbs order table"]);
$table->addColumn('line', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
$table->addColumn('item', 'integer', ['null' => false, 'default' => '0', 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'line']);
$table->addColumn('size_code', 'string', ['null' => false, 'limit' => 1, 'collation' => "latin1_swedish_ci", 'encoding' => "latin1", 'after' => 'item']);
$table->addColumn('quan', 'integer', ['null' => false, 'default' => '0', 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'size_code']);
$table->addColumn('orderID', 'string', ['null' => false, 'limit' => 255, 'collation' => "latin1_swedish_ci", 'encoding' => "latin1", 'after' => 'quan']);
$table->addColumn('date', 'timestamp', ['null' => false, 'default' => 'CURRENT_TIMESTAMP', 'after' => 'orderID']);
$table->addColumn('ordnum', 'integer', ['null' => true, 'default' => '0', 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'date']);
$table->addColumn('browser_info', 'text', ['null' => true, 'limit' => 65535, 'collation' => "latin1_swedish_ci", 'encoding' => "latin1", 'after' => 'ordnum']);
$table->save();
if($this->table('bulbs_orders')->hasIndex('item')) {
     $this->table("bulbs_orders")->removeIndexByName('item');
}
$this->table("bulbs_orders")->addIndex(['item','size_code','orderID','ordnum'], ['name' => "item", 'unique' => true])->save();
```

When I run the migration on an SQLite database, it creates the table only with an `id` column:
![screen shot 2017-07-25 at 3 09 49 pm](https://user-images.githubusercontent.com/1420419/28589296-7895db16-714b-11e7-9473-a3ffb32b9bcf.png)

If I remove the `'identity' => 'enable'` from the first column definition (for column "line"), the migration will create the table and all columns, but "line" will not be a primary key:
![screen shot 2017-07-25 at 3 10 14 pm](https://user-images.githubusercontent.com/1420419/28589317-8622aab6-714b-11e7-9531-242dc3f21b09.png)

**Comment by claytonrcarter** [comment]
Altering the first line of the migration to remove the `primary_key` option allows the migration run as expected:
```php
$table = $this->table("bulbs_orders", ['id' => false, 'engine' => "MyISAM", 'encoding' => "latin1", 'collation' => "latin1_swedish_ci", 'comment' => "bulbs order table"]);
```

**Comment by odan** [comment]
Hi! What happens if you run the migration on an MySQL database?

**Comment by claytonrcarter** [comment]
Hmm. If I run the "fixed" migration on MySQL it gives me `[PDOException (42000)] SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there can be only one auto column and it must be defined as a key`. If I add `primary_key` back into the table definition parameters, it appears to work for MySQL.

**Comment by odan** [comment]
Then I think this is a phinx related bug in combination with SQLite.

**Comment by odan** [comment]
It looks like a bug in phinx and should be fixed there. I close this issue for now.
