### ISSUE TITLE
Use tablename from phinx.yml config file instead of hardcode value

### ISSUE THREAD

**Issue by FallDi** [odan/phinx-migrations-generator#21]
In the following code `phinxlog` table name is hardcoded.

https://github.com/odan/phinx-migrations-generator/blob/3883f8169b2d69638cf818c403c16e2beb113c24/src/Migration/Adapter/Generator/PhinxMySqlGenerator.php#L189

I suggest following improvement: use tablename from `phinx.yml` config file

**Comment by odan** [comment]
Hi @FallDi Just added this new feature. Please run `composer update` and give me a feedback.

**Comment by FallDi** [comment]
@odan thank you for quick reply!

I added small notice https://github.com/odan/phinx-migrations-generator/commit/b99f453b5272c7eb5f9e086a388636e6a4e9ba71#commitcomment-25177214.

Looks  really good, thank you for package!

**Comment by odan** [comment]
That's right, this setting is under `environments`. I fixed it.
http://docs.phinx.org/en/latest/configuration.html#external-variables

**Comment by FallDi** [comment]
Amazing! Thank you
