### ISSUE TITLE
Problem with primary keys

### ISSUE THREAD

**Issue by pulse14** [odan/phinx-migrations-generator#22]
The script generate something like that

```php
 $table = $this->table("asset_templates", ['id' => false, 'primary_key' => ["id", "unity_object_id"], 'engine' => "InnoDB", 'encoding' => "latin1", 'collation' => "latin1_swedish_ci", 'comment' => ""]);
 $table->addColumn('unity_object_id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_BIG, 'precision' => 19, 'after' => 'id']);
````

It causes a bug because id is not created.

**Comment by odan** [comment]
As far as I can tell, this feature (multiple primary keys) seems to be a bug in phinx. This bug is very old (2012) and there doesn't seem to be a real solution yet.

https://github.com/cakephp/phinx/issues/28
