### ISSUE TITLE
If table has id, changeColumn() throws error when reverting

### ISSUE THREAD

**Issue by bramkorsten** [odan/phinx-migrations-generator#29]
After adding a new table to my database, and generating the migrate script for it, everything seemed well. the actual migration went flawlessly, and worked every time.

The error happens when I try to revert those migrations. The generated script checks whether a column named `'id'` already exists, and modifies it if it does. The problem is that the `change()` method cannot handle `changeColumn()`, and crashes showing the following error.

`Fatal error: Uncaught Phinx\Migration\IrreversibleMigrationException: Cannot reverse a "changeColumn" command in [PATH]\robmorgan\phinx\src\Phinx\Db\Adapter\ProxyAdapter.php:228`

This is the generated migrate script:

```php
    <?php

    use Phinx\Migration\AbstractMigration;
    use Phinx\Db\Adapter\MysqlAdapter;

    class AddNewsTable extends AbstractMigration
    {
        public function change()
        {
          $table = $this->table("news", ['engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => ""]);
      $table->save();
      if ($this->table('news')->hasColumn('id')) {
          $this->table("news")->changeColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable'])->update();
      } else {
          $this->table("news")->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable'])->update();
      }
      $table->addColumn('title', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id'])->update();
      $table->addColumn('body', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'title'])->update();
      $table->addColumn('created_at', 'datetime', ['null' => false, 'default' => 'CURRENT_TIMESTAMP', 'after' => 'body'])->update();
      $table->save();
    }
    }
```

Is deleting and recreating the column a possible solution?

Great project and thanks!

**Comment by odan** [comment]
Hi @bramkorsten Well, reverting a migration is possible (in the theory), but not possible in every case and not 100% supported by Phinx itself. Even simple reverse operations will fail with a error message like this. That's why I decided to not implement a reverse migration feature. 

> Is deleting and recreating the column a possible solution?

In the development environment this may still be ok, but in production I wouldn't do it. I would recommend never reverting a migration, as it is only too dangerous and error-prone. A backup before migration would be the safer method.

**Comment by bramkorsten** [comment]
Ah I see... But isn't that the whole 'shablam' about migrations? Being able to rollback to say a previous version or something like that? It seems that for a simple migration like creating a simple table, rolling back shouldn't be an issue.

I know that I could always go back to writing the `up()` and `down()` scripts myself, but your tool seemed like the perfect way to handle this for me.

Anyway, thanks for the help!

**Comment by odan** [comment]
>But isn't that the whole 'shablam' about migrations?

For me, migrations are an important part of continuous integration (CI) and continuous deployment (CD). The primary goal is to automate all these deployment steps. Today it is simply too complex and error-prone to manually migrate all servers to a defined database schema version. Even if you manage to migrate the schema back, this does not mean that this is also possible with your **data**.

If you really need a down() method, of course you still have the possibility to implement it yourself. 

So far I have seen no need to generate a `down()` method. If there are more requests in this regard, I could imagine implementing it.
