### ISSUE TITLE
Bit Value Literals

### ISSUE THREAD

**Issue by pukkancs** [odan/phinx-migrations-generator#32]
Hi, 
bit value literals are stored as  ```b'0'``` which causes issues with the generated migrations as most of the places for the PHP strings the generator is using single quotes as well.

I noticed it in default values but worth investigating with the other values as well. 

I created a pull request to fix it for `defaults`.

**Comment by odan** [comment]
Hi @pukkancs Thanks for your feedback. My impression is that bit literals are rarely used. Of course I merged your PR with pleasure, because apparently in very rare cases bit literals are used. Where exactly do you think this could become a real problem? Can you give us some more examples? Thanks.

**Comment by pukkancs** [comment]
Hi @odan,

Thanks, for the quick response. Yes, I guess bit literals are not commonly used, this is the first time I encountered them as well :) 

I am not sure about any real life use cases, as it is not likely that I would use bit literals myself. Where it might be possible though is wherever you are able to define a value. 

I am thinking maybe `enum` values.  (I am not sure about this, also who would do something like that, but one of the purpose of your library is to be able to set up initial migration for existing db, and in existing databases, magical things reside :) Like bit default values instead of bool :D)

**Comment by odan** [comment]
I've decided to close this ticket for now.  If there's more demand, I'll reopen it. Thank you.
