### ISSUE TITLE
Generate initial migrations per table, instead of one giant migration

### ISSUE THREAD

**Issue by hskrasek** [odan/phinx-migrations-generator#35]
We are looking to implement a database migration system for an already existing database. Is there anyway to generate initial migrations per table, instead of one giant migration with all the tables?

It's a huge database with about 71 tables, so that initial migration file gets to be pretty huge and unruly

**Comment by odan** [comment]
Hi @hskrasek 

> Is there anyway to generate initial migrations per table

No, that's not planned either.

> It's a huge database with about 71 tables, so that initial migration file gets to be pretty huge and unruly

I don't see a issue with that. Is this a technical problem for you or is it an "aesthetic" aspect? If you do not want these large files, you can of course manually split the initial file into several small PHP files.

**Comment by hskrasek** [comment]
@odan Not sure if really a technical issue, though some of the data the generator creates doesn't work first execution so it takes some extra time parsing through the large files to find and resolve the errors. But not impossible to do.

My experience is with a package that generates Laravel migrations from an existing database, which did a migration per table, which gave you a migration history of X creations per table. 

But while it would take more time, obviously generating the massive init migration and then splitting them into individual files is doable

**Comment by odan** [comment]
> some of the data the generator creates doesn't work first execution

That sounds like a bug in the generator. Why don't you create an issue for that?

> migration per table

I like this idea. Maybe we could solve this with a new (optional) parameter/settting for the generator. I'll see what I can do.

**Comment by odan** [comment]
Most initial migration issues have been fixed since v4. For this reason I close this ticket. Thank you for your feedback.
