### ISSUE TITLE
Using phinx-migrations-generator with drupal

### ISSUE THREAD

**Issue by liaogz82** [odan/phinx-migrations-generator#38]
I am looking for a database migration generator for Drupal. Do you have any documentation and any experience on how to use this library for drupal?

**Comment by odan** [comment]
Hello @liaogz82 

Phinx and the phinx-migrations-generator is framework independent (agnostic). This means it should work for Drupal too. I don't know Drupal very well, but the installation and usage should be the same. What have you tried so far?

**Comment by liaogz82** [comment]
Yes I just managed to get it to work. It is that I need to update the yml
file. Thanks!
