### ISSUE TITLE
Defaults are not properly dealt with on MariaDB 10.2.7+ (including NULL)

### ISSUE THREAD

**Issue by alxgb** [odan/phinx-migrations-generator#42]
I know it says in the README that the library supports MySQL 5.7+, but since MariaDB is commonly used to replace MySQL (e.g [in linux distros](https://mariadb.com/kb/en/library/distributions-which-include-mariadb/), notably CentOS/Debian...), or at the very least the most common replacement for MySQL, I thought it'd be worth a mention.

MariaDB 10.2 supports expressions on defaults, which MySQL does not, and from MariaDB 10.2.7 onwards, the information schema default column is now evaluated and stored as an expression, and not a string (see: https://mariadb.com/kb/en/library/information-schema-columns-table/)

To be explicit, from MariaDB 10.2.7+: 

- When the column default is NULL, the COLUMN_DEFAULT column has a string value of "NULL". This breaks detection of NULL defaults, because they're treated as a "NULL" string.
- When the column default is 'ABC', the COLUMN_DEFAULT column has a string value of "'ABC'", *simple quotes included*. This also probably breaks things, but I haven't tested it, as I ran into the NULL defaults problem first.

There's of course no way to handle both MySQL and MariaDB at the same time unless the engine is detected. I suppose `SELECT @@GLOBAL.version;` could be parsed and defaults parsed accordingly, but I'm not sure if there's an interest from your side to support MariaDB moving forward.

Edit: Alternatively, a **mariadb_new_default_schema** option could be added (or some name like that), which is more reliable than parsing a server variable

**Comment by odan** [comment]
Hi @alxgb Thank you very much for your good feedback. 

The question is, what if you run MariaDB in dev and MySQL on the production server? Then the generated migration would be optimized for MariaDB, but "fail" on the Prod server.

**Comment by alxgb** [comment]
Hi,

Indeed, I hadn't really considered that scenario (and I guess, the inverse - a developer has MySQL on their PC but there's MariaDB in production). Ok, let's ditch mariadb_new_default_schema then, here's another idea:

New option, _treat_defaults_as_expr_, with 3 levels:
0: Generated code as it is now
1: Generated code assumes all defaults are expressions, and doesn't quote them
2: Dynamically query the engine in order to use expr or no expr. The 'default' options in this case would not be a literal, but a function call to a code-generated default() function that yields the right default based on the schema

How about that? I didn't want to add the dynamic query always since it's some overhead and there's a chance it may not be 100% guaranteed to work (e.g if the user altered the version variable - which I'm not sure right now is possible).

**Comment by odan** [comment]
Due to time reasons I cannot offer support for MariaDB. For this reason I have to close the ticket. Thank you very much.
