### ISSUE TITLE
Multi column primary keys cannot be generated

### ISSUE THREAD

**Issue by odan** [odan/phinx-migrations-generator#46]
I am using the latest version (3.1.0) and unfortunately have the same issue: Multi column primary keys cannot be generated. The problem is, that after every addColumn() in the generated migration file, there is a call to save(). 

The table:
```mysql
CREATE TABLE `test` (
  `pk1` int(11) unsigned NOT NULL,
  `pk2` int(11) unsigned NOT NULL,
  PRIMARY KEY (`pk1`,`pk2`)
) ENGINE=InnoDB
```
Will produce a migration file like this:
```php
...
$table = $this->table("test", ['id' => false, 'primary_key' => ["pk1", "pk2"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Dynamic"]);
$table->addColumn('pk1', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'signed' => false])->save();
$table->addColumn('pk2', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'signed' => false, 'after' => 'pk1'])->save();
$table->save();
...
```

Which will then, when running the migration with phinx, produce the mysql query (output via -vvv option):
```mysql
 -- createTable('test')
CREATE TABLE `test` (`pk1` INT(11) unsigned NOT NULL, PRIMARY KEY (`pk1`,`pk2`)) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT=''  ROW_FORMAT=Dynamic;
```

To fix this, the save() call after the addColumn() calls should be removed, as there is a final $table->save() call anyways.
```php
$table = $this->table("test", ['id' => false, 'primary_key' => ["pk1", "pk2"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Dynamic"]);
$table->addColumn('pk1', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'signed' => false]);
$table->addColumn('pk2', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'signed' => false, 'after' => 'pk1']);
$table->save();
```

**Comment by LightningMD** [comment]
I know this was previously closed, but I wanted to comment because I'm getting an error with multiple primary keys, and removing the $table->save() immediately following did not resolve it for me.  It still errors out on the second PK saying that the column doesn't exist.  Any advice here? Thank you!

**Comment by odan** [comment]
Hello, which version do you use?

**Comment by LightningMD** [comment]
I have 3.1 Odan  /  0.10.6 Robmorgan

**Comment by odan** [comment]
This fix is available since v.4 of this package. Can you please try to update to the latest version (4.x)?

**Comment by LightningMD** [comment]
Shoot, it will force me to update my PHP version as well. I'm using PHP 7.0.33 right now. Thank you so much for replying to me so quickly! I will update it if I have to, but wondering if there is another workaround? I'm going to try writing a key change migration after the initial.  Thank you!

**Comment by LightningMD** [comment]
Ok adding the key change after the table save worked! Thanks again for your attention and for the script!!
