### ISSUE TITLE
No migration paths set in your Phinx configuration file.

### ISSUE THREAD

**Issue by spagu** [odan/phinx-migrations-generator#50]
Hi,  I am getting this kind of error with PHP7.3 :

```
./bin/phinx-migrations generate
Phinx by CakePHP - https://phinx.org. 0.10.6

using config file ./phinx.php
using config parser php
using migration paths
 - /usr/local/www/test/database/migrations
using seed paths
 - /usr/local/www/test/database/seeds
warning no environment specified, defaulting to: current
using database services
using config file /usr/local/www/test/phinx.php

In GenerateCommand.php line 105:

  No migration paths set in your Phinx configuration file.

```
Problem that I spoted is in this line: 
`   $migrationsPaths = !is_array($migrationsPaths) ? (array)$migrationsPaths : [];`
this just make variable empty.

**Comment by odan** [comment]
Please try updating to v4.0.2 and tell me if it works now.

**Comment by dsielert** [comment]
definitely still broken in 4.0.2

**Comment by odan** [comment]
With v4.0.3 this should be fixed for php 7.3. Please give me a feedback.

**Comment by dsielert** [comment]
Using php 7.2 and it is the same broken in 4.0.1 as well.. that line @spagu mentioned is resetting the migrations array to a blank array

**Comment by dsielert** [comment]
Seems to me that line ought to be 
```
$migrationsPaths = !is_array($migrationsPaths) ? (array)$migrationsPaths : )$migrationsPaths;
```

**Comment by odan** [comment]
@dsielert Yes, this line should be fixed since v.4.0.3.

**Comment by spagu** [comment]
confirmed it is fixed. Thanks guys !!
