### ISSUE TITLE
Overwrite schema file or not?

### ISSUE THREAD

**Issue by D4V3M0NK** [odan/phinx-migrations-generator#51]
I've been using phinx and phinx-migrations for a while now and I've always selected "N" to **overwriting the schema file** (the last prompt) as I'm anal about deleting anything.  Is it possible to get a little more information as to the differences between these two?

I'm _guessing_ that :
- answering "N" will place all prior migrations into the newly created one, so that if I ever lost a prior migration, I could still use the latest and it would've included the prior. This means that all migration files will slowly increase in file size
- Answering "Y" will only write the changes that were seen into the migration file, ignoring all others. This means that a small change (ie field rename) would generate a small migration file, whereas a brand new table would generate a larger migration file.

**Comment by odan** [comment]
Hello! Here you can find more informations about the usage: https://github.com/odan/phinx-migrations-generator/issues/8#issuecomment-295460712

The `schema.php` file contains all table- and column-definitions of the database after the new migration script has been generated. The file size only depends on the number of tables and columns of the latest schema.

* answering "N" will keep the content of the file `schema.php` unchanged.

* answering "Y" will overwrite the content of `schema.php` with the latest database schema definitions. This allows you to generate a "diff" on the next run.
