### ISSUE TITLE
Default add double quotes

### ISSUE THREAD

**Issue by ruudboon** [odan/phinx-migrations-generator#52]
When generating migrations I'm having errors wile deploying changes.
Looks like extra quotes are added to the migration file (not the schema)
```
->addColumn('email_verified', 'char', [
                'null' => false,
                'default' => '\'N\'',
                'limit' => 1,
                'collation' => 'utf8_unicode_ci',
                'encoding' => 'utf8',
                'after' => 'name',
            ])
```
and 
```
->addColumn('password', 'char', [
                'null' => true,
                'default' => 'NULL',
                'limit' => 60,
                'collation' => 'utf8_unicode_ci',
                'encoding' => 'utf8',
                'after' => 'new_email',
            ])
```

**Comment by odan** [comment]
Hi @ruudboon! Do you use MySQL or MariaDB?

**Comment by ruudboon** [comment]
@odan MariaDB Could this be related?

**Comment by odan** [comment]
Yes, there are some differences, especially in the `null` default values.

Although MariaDB is not officially supported, I have tried this table schema with MariaDB:
```
CREATE TABLE `test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email_verified` char(1) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```

The genderated code for the column `email_verified` looks OK and works, even with MariaDB:

```php
->addColumn('email_verified', 'char', [
            'null' => false,
            'limit' => 1,
            'collation' => 'utf8_unicode_ci',
            'encoding' => 'utf8',
            'after' => 'id',
        ])
````

You see, there is no `'default' => '\'N\'',` property here.
Could you please show me the original table schema, or at least the exact definitions for the column `email_verified`? Then maybe I can reproduce the behavior.
