### ISSUE TITLE
Multiple migration folders crashes

### ISSUE THREAD

**Issue by curtiscarlson** [odan/phinx-migrations-generator#53]
Having multiple migration folders seems to crash this tool.  

```
In AbstractCommand.php line 313:

  Migration directory "{app/db/migrations,vendor/curtiscarlson/module/db/migrations}" does not exist
```

I am on windows so that might be part of the issue

**Comment by curtiscarlson** [comment]
ok actually it has nothing to do with multiple folders.  just working through this:  

```
Migration directory "{vendor/curtiscarlson/module/db/migrations}" does not exist
```

it surely does, and works for migrations in plain phinx.  will report back after more digging.

**Comment by curtiscarlson** [comment]
OK, I got the thing to run by setting the absolute migration path just like in the readme.  This is inconsistent with the phinx.php configuration.....

**Comment by odan** [comment]
Well, the phinx "multiple directories patterns" like `{migrations,migrations2}` are not supported at the moment. Also single paths with curly braces like `"{migrations}"` are not supported. It's only possible to pass relative or absolute paths.

I think it would not make much sense to generate the same migration, multiple times, in different locations. But maybe I missed something? What would be the use case?

But it should be possible to provide multiple migration paths by using an `array` in your configuration file. In this case the migration generator would pick the first directory as migration path.

**Comment by curtiscarlson** [comment]
Well, the use case is that I have two migration folders (one for my common app stuff like users, roles, uploads, dates, queue, etc., and the second folder is in a package, it is the domain package, in a separate repo, containing the migrations for the actual business logic.  Same for seeds.  So I had that working.  And it works great, I love how it asks you which folder to generate a file into.  But then I wanted to try to reverse engineer an old database, and so I had to change the configuration to do that.  No big deal, I ran the reverse migration (it only needs to be done once), and put the settings back.  I just thought you would like to know that the reverse migration settings aren't compatible with the rest of the application's settings.

**Comment by odan** [comment]
It is also possible to "overwrite" the path settings from the config file by using the console `--path` parameter only in case you want to generate a migration. `vendor/bin/phinx-migrations generate --path app/db/migrations`.

> I just thought you would like to know that the reverse migration settings aren't compatible with the rest of the application's settings.

Indeed, not every phinx migration (generated or written by hand) can be reverted. But's thats another topic. Thanks for your feedback :-)
