### ISSUE TITLE
Option to delete entries for unchanged tables

### ISSUE THREAD

**Issue by JoyceBabu** [odan/phinx-migrations-generator#55]
Currently, the generated migration scripts includes a `$this->table(...)->save()` call for every table, including the unmodified tables. I have a database with 215 tables.

Is it possible to filter out the entries for unmodified tables, so that it is easier to review the generated migration code?

**Comment by odan** [comment]
Everytime you call the generate command, the generator creates a diff by comparing the current database schema with the schema stored in `schema.php`. If your diff contains all tables, the file `schema.php` is empty or does not exists. Are you sure, that `schema.php` is "up to date"?

**Comment by JoyceBabu** [comment]
The `schema.php` is up to date. When there are no changes, I get the message

> No database changes detected.

But when I add a new column to an existing table, the generated migration contains an entry for every existing table.

From reading the code, `PhinxMySqlGenerator::getTableMigrationTables` does not check whether the table is modified or not.

**Comment by DavidMernin** [comment]
I am experiencing the same problem.  I just rename a column in one table and I get a migration for every table.

**Comment by odan** [comment]
It should be fixed now. Please update to the latest version and give me a feedback. Thanks.

**Comment by DavidMernin** [comment]
Works perfectly now!  Thank you! =)
