### ISSUE TITLE
Bump phinx dependency

### ISSUE THREAD

**Issue by killua-eu** [odan/phinx-migrations-generator#59]
Phinx 0.11 was released today to fix a breaking change in symphony/console - see
https://github.com/cakephp/phinx/issues/1585

Would you kindly bump the migration generator to accept phinx ^0.11 as well?

Thanks lots, P

**Comment by odan** [comment]
The phinx version has been changed from ^0.10 to ^0.11.

**Comment by odan** [comment]
@cesar1983 For now PHP 7.2 is not really necessary. The minimum PHP version will be 7.1 in the next release.
