### ISSUE TITLE
Indexes are generated mostly as unique

### ISSUE THREAD

**Issue by lucien144** [odan/phinx-migrations-generator#6]
[This check](https://github.com/odan/phinx-migrations-generator/blob/master/src/Migration/Adapter/Generator/PhinxMySqlGenerator.php#L937) returns always `FALSE` because `isset()` is case sensitive when testing assicative arrays ([reference](http://php.net/manual/en/function.isset.php#87521)).

As `SHOW INDEX FROM {table};` don't usually return columns names in uppercase, this `isset($indexData['NON_UNIQUE']) == isset($indexData['Non_unique'])` is not true.

As a fix I suggest to use `array_map` and normalize all columns names to uppercase.

Happy to do the PR.

**Comment by odan** [comment]
Right, the index names should be 'Non_unique', 'Key_name' and 'Index_type'. 
Using array_map is not necessary. Can you just rename the index names please?
