### ISSUE TITLE
Cross database FKs not being generated

### ISSUE THREAD

**Issue by renatoaraujoc** [odan/phinx-migrations-generator#64]
Hello!

I have fully implemented a project using this library and I happen to have many mysql databases running in the same instance and _referencing each other_.
What happens is that everything works pretty fine **except** for cross database foreign-key constraints, I will supply a local example (columns are in portuguese).

Consider this table and **note the first constraint** (which references another table prefixed with another database name):

```sql
CREATE TABLE `planos_ambitos` (
 `visitantes_planos_id` bigint(20) unsigned NOT NULL,
 `ambitos_id` int(10) unsigned NOT NULL,
 PRIMARY KEY (`visitantes_planos_id`,`ambitos_id`),
 KEY `ambitos_id` (`ambitos_id`) USING BTREE,
 KEY `visitantes_planos_id` (`visitantes_planos_id`) USING BTREE,
 CONSTRAINT `planos_ambitos_ambitos_id_fk` FOREIGN KEY (`ambitos_id`) REFERENCES `geo`.`ambitos` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT `planos_ambitos_visitantes_planos_id` FOREIGN KEY (`visitantes_planos_id`) REFERENCES `visitantes_planos` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```
Upon executing `phinx-generator generate`, this is generated:
```php
$this->table('planos_ambitos', [
    'id' => false,
    'primary_key' => ['visitantes_planos_id', 'ambitos_id'],
    'engine' => 'InnoDB',
    'encoding' => 'utf8',
    'collation' => 'utf8_general_ci',
    'comment' => '',
    'row_format' => 'DYNAMIC',
])
->addColumn('visitantes_planos_id', 'biginteger', [
    'null' => false,
    'limit' => MysqlAdapter::INT_BIG,
    'signed' => false,
])
(... cut for brevity ...)
->addForeignKey('visitantes_planos_id', 'visitantes_planos', 'id', [
    'constraint' => 'planos_ambitos_visitantes_planos_id',
    'update' => 'CASCADE',
    'delete' => 'CASCADE',
])
->create();
```
This is missing: 
```php
->addForeignKey('ambitos_id', 'geo.ambitos', 'id', [
    'constraint' => 'planos_ambitos_ambitos_id_fk',
    'update' => 'CASCADE',
    'delete' => 'CASCADE',
])
```
Versions (all latest as of this issue):
```
phinx 0.11.1
phinx-migrations-generator 4.3.0
```
Would love for an input on this matter, you library rocks!

Renato

**Comment by renatoaraujoc** [comment]
I was digging thru the issue here and found that on the file below:
https://github.com/odan/phinx-migrations-generator/blob/eb5e996356547377e66ff6f07f5b4f2652b0682e/src/Migration/Adapter/Database/MySqlSchemaAdapter.php#L375
I analyzed the SQL and made some corrections and now it correctly fetches all the foreign keys, including those referenced on another database table. I just included `cRefs.UNIQUE_CONSTRAINT_SCHEMA as REFERENCED_DATABASE` as a column to have the referenced database value returned and removed the `AND refs.REFERENCED_TABLE_SCHEMA=cols.TABLE_SCHEMA`

```sql
SELECT cols.table_name, 
       cols.column_name, 
       cRefs.constraint_name, 
       cRefs.unique_constraint_schema AS REFERENCED_DATABASE, 
       refs.referenced_table_name, 
       refs.referenced_column_name, 
       cRefs.update_rule, 
       cRefs.delete_rule 
FROM   information_schema.COLUMNS AS cols 
       left join information_schema.key_column_usage AS refs 
              ON refs.table_schema = cols.table_schema 
                 AND refs.table_name = cols.table_name 
                 AND refs.column_name = cols.column_name 
       left join information_schema.table_constraints AS cons 
              ON cons.table_schema = cols.table_schema 
                 AND cons.table_name = cols.table_name 
                 AND cons.constraint_name = refs.constraint_name 
       left join information_schema.referential_constraints AS cRefs 
              ON cRefs.constraint_schema = cols.table_schema 
                 AND cRefs.constraint_name = refs.constraint_name 
WHERE  cols.table_name IN ( %s ) 
       AND cols.table_schema = DATABASE() 
       AND refs.referenced_table_name IS NOT NULL 
       AND cons.constraint_type = 'FOREIGN KEY' 
```

Now it should be some hotfix to include the foreign-keys appended with it's database name if it's a foreign database (actual db != referenced_db) and keep the current foreign-key gereneration for same database intact.

**Comment by odan** [comment]
Hi @renatoaraujoc 

The current schema.php is free of any database name, because of the version control (like git and SVN) and the different development and production database names. Referencing to fix database names could lead to quite big issues in many cases because the hash would be different on every (developer) machine. This would lead to invalid migrations for other users.

**Comment by renatoaraujoc** [comment]
Alright, I understand your motivation to make these migrations database-safe but then we have to look deeper and recognize that cross-database foreign key is an existing feature of many dbs and a migration tool should be able to handle all situations so I'd like to propose something considering the current limitations, considering that:

1. There are systems where many databases in the same instance exist.
   1.1 These that databases can share foreign keys
2. These databases have a fixed name (which happen in the vast majority of cases)
3. We have people already in the current migration method (nameless database)

We can make a opt-in flag, maybe:
```yaml 
immutable_database_naming:
  enabled: true # default false for backwards compatibility
  enable_cross_foreign_key: true # default false (will only work if enabled above is true)
```

When `immutable_database_naming.enabled` is `true`, migrations will consider that the databases will always have the same name, so migrations can even consider stuff like `CREATE DATABASE XYZ` can be generated when the first migration is generated and when `immutable_database_naming.enable_cross_foreign_key` is `true`, the cross-db foreign-key is enabled.

What do you think?

Renato

**Comment by renatoaraujoc** [comment]
I'm closing this, I forked your project and made the changes o my own. Thank you!
