### ISSUE TITLE
Question: phinx rollback and migrations

### ISSUE THREAD

**Issue by D4V3M0NK** [odan/phinx-migrations-generator#66]
Pretty much every time I make a change to my database, I run a migration, just so that I can be somewhat granular on exactly what has happened to my database by briefly reading the list of migrations in date order.

For the first time (been using PMG for about a year now) I have to use the `rollback` command as I made a mistake which was recorded in the last migration. For example, today I have the following migrations:

- YYYYMMDD175816_update_folder_to_varchar256
- YYYYMMDD180534_rename_createdby_to_orderid
- YYYYMMDD214148_add_status_to_t1_and_t2

_Every time I run the PMG `generate` command I choose to override my schema.php file. Additionally, I don't use breakpoints._

I wanted to revert back to the 180534 version, and as it was the penultimate migrate, `phinx-migrations rollback` was all I needed.

1. Can I now safely delete the 214148 file without screwing anything else up, including later migrations? Or do I leave it there and somehow the next time I run a migration, it'll just be ignored? _(I note that the phinxlog table shows the latest as being 180534)_
1. Can I safely assume schema.php is back to the 180534 version?

Should I be doing anything else??

**Comment by D4V3M0NK** [comment]
As a note, it appears that my `schema.php` file still has the changes in it from the 214148 migration ... I take it that this would have to be a manual edit to remove them?

**Comment by odan** [comment]
Phinx has this rollback command.

    phinx rollback -e development
 

You can find further details in the documentation. [Phinx rollback][1]


  [1]: http://docs.phinx.org/en/latest/commands.html#the-rollback-command

After you "roll backed" the local (development) changes and you don't need it in production, you should revert the local schema.php file from your version control (git) because schema.php will not be reverted by the phinx rollback command.

**Comment by D4V3M0NK** [comment]
I hadn't checked in the changes before wanting to roll back, but it appears that everything is ok - and I certainly appreciate the confirmation Daniel.
