### ISSUE TITLE
Make setting `schema_file` configurable via phinx.yml

### ISSUE THREAD

**Issue by JoyceBabu** [odan/phinx-migrations-generator#73]
My `schema.php` is too long (around 65K lines) and it is causing `PHP-CS-Fixer` in my post commit hook to fail due to hitting memory limit. I would like to change the file extension to a lint only extension.

Will you accept a PR to make the value of `schema_file` configurable via phinx configuration file?

**Comment by JoyceBabu** [comment]
I just noticed that schema file can be a `.php` or `.json` file. But I cannot find an option to change the schema file, since it is hard coded as `schema.php` in `GenerateCommand::getSchemaFilePath`.

**Comment by odan** [comment]
@JoyceBabu The json support has been removed long time ago. Please exclude the `schema.php` from scanning.

**Comment by JoyceBabu** [comment]
> @JoyceBabu The json support has been removed long time ago. Please exclude the `schema.php` from scanning.

Did you mean you are planning to remove it in future? Since I am already using a custom `GenerateCommand`, I tried overriding `getSchemaFilePath` to return `schema.json` instead of `schema.php`, and it worked as expected.

`MigrationGenerator::saveSchemaFile` and `MigrationGenerator::getSchemaFile` still contains the code for handling the file correctly, depending on the extension.

**Comment by odan** [comment]
> Did you mean you are planning to remove it in future? 

Well, I tried it ;-)

Please create a PR to make the `schema_file` configurable via phinx configuration file.

**Comment by JoyceBabu** [comment]
> Well, I tried it ;-)

 😀

Why did you chose PHP native array over JSON? Was it for removing the dependency on JSON module? Is there a noticeable performance overhead in parsing JSON? Isn't JSON a better format in this case, since the data is not exactly source code?
