### ISSUE TITLE
Allow Symfony 5

### ISSUE THREAD

**Issue by Capenus** [odan/phinx-migrations-generator#75]
Symfony 5 was [just released](https://symfony.com/blog/symfony-5-0-0-released). Is it possible to allow Symfony 5 in [composer.json](https://github.com/odan/phinx-migrations-generator/blob/04ed94a282c41cb34c417f98fb2796f2a2593c5e/composer.json#L19)?

**Comment by odan** [comment]
Yes, of course. I will add it.

**Comment by odan** [comment]
Done
