### ISSUE TITLE
The utf8 string is encoded. Why do you do this?

### ISSUE THREAD

**Issue by jiuwuxiaohun** [odan/phinx-migrations-generator#76]
```
    protected function prettifyArray(array $variable, int $tabCount): string
    {
        $encoder = new PHPEncoder();
        
        return $encoder->encode($variable, [
            'array.base'    => $tabCount * 4,
            'array.inline'  => true,
            'array.indent'  => 4,
            'array.eol'     => "\n",
            'string.escape' => false,//I modified this
            'string.utf8'   => true,//I modified this
        ]);
    }
```
我这边是中国用户，汉字被编码为了”\xXX\xXX”这种情况。
I'm a Chinese user, and the Chinese characters are encoded as "\xXX\xXX".
After viewing the documentation of PHPEncoder, add two parameters to solve.

**Comment by odan** [comment]
The PHPEncoder (external library) escapes all strings to printable characters by default.

Can you please create a PR to fix this issue here?

**Comment by jiuwuxiaohun** [comment]
#77   I submitted this.
----
For the first pull request, please check if there is any problem with mine. I originally installed my own modified branch in composer VCS. If you merge, I can switch to the official composer source again.

**Comment by odan** [comment]
Thanks. Your fix has been merged.
