### ISSUE TITLE
Failure on generated columns 

### ISSUE THREAD

**Issue by killua-eu** [odan/phinx-migrations-generator#78]
Hi Daniel,

I got a table created as

```
CREATE TABLE t_assets_items (
c_uid int(11) NOT NULL,
c_data json NOT NULL,
stor_name varchar(255) COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (json_unquote(json_extract(c_data,'$.data.item'))) VIRTUAL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

running the migrations generator, I end up with

```
        $this->table('t_assets_items', [
                'id' => false,
                'engine' => 'InnoDB',
                'encoding' => 'utf8mb4',
                'collation' => 'utf8mb4_unicode_ci',
                'comment' => '',
                'row_format' => 'DYNAMIC',
            ])
            ->addColumn('c_data', 'json', [
                'null' => false,
            ])
            ->addColumn('c_uid', 'integer', [
                'null' => false,
                'limit' => MysqlAdapter::INT_REGULAR,
                'after' => 'c_data',
            ])
            ->addColumn('stor_name', 'string', [
                'null' => true,
                'limit' => 255,
                'collation' => 'utf8mb4_unicode_ci',
                'encoding' => 'utf8mb4',
                'after' => 'c_uid',
            ])
            ->create();
```

with the `stor_name` column ending up with some wrong code. Would you please look into this one? I'm ready to help with tests etc., just let me know.

**Comment by odan** [comment]
Hi @killua-eu 

The column `stor_name` is a so called "generated column", which are are not fully supported by Phinx.

`GENERATED ALWAYS AS (json_unquote(json_extract(c_data,'$.data.item'))) VIRTUAL`

I think this PR will allow us to add those columns, if it gets merged.

* https://github.com/cakephp/phinx/pull/1311 
* https://github.com/cakephp/phinx/issues/1276

**Comment by killua-eu** [comment]
Ahh. So the https://github.com/cakephp/phinx/pull/1175 is not enough here to get this done right? Btw, can the phinx-migration-generator generate raw sql changes too? That might be a workaround.

**Comment by odan** [comment]
At the moment it's not clear for me how to use this new feature to generate an output like `GENERATED ALWAYS AS (json_unquote(json_extract(c_data,'$.data.item'))) VIRTUAL`

Do you have an working example?

> Btw, can the phinx-migration-generator generate raw sql changes too? That might be a workaround.

This would be a nice feature.

**Comment by killua-eu** [comment]
I'll do some more tests in the week (with respect to the new feature) & let you know. Raw sql would be imho awesome.

**Comment by killua-eu** [comment]
Did some trial and error. Couldn't really progress on using the phinx's literal class towards the wanted result. I asked the phinx devs now. What naturally works is plain sql ... after the create() statement, I just added an execute()

```
// generated code here
 ->create();
$this->execute("ALTER TABLE `t_calendar_sources` DROP `c_flag_deleted`; ALTER TABLE `t_calendar_sources` ADD `c_flag_deleted` boolean GENERATED ALWAYS AS (IF((json_unquote(json_extract(`c_attr`,'$.deleted'))) = 'true', 1, 0)) VIRTUAL NOT NULL;");
```

So maybe  #80 is a solution unless I have some progress here

**Comment by killua-eu** [comment]
I tried some more and failed beautifully. I guess supporting plain SQL is the best way around this then.

**Comment by odan** [comment]
Ok, thank you very much for exploring the existing possibilities. So I think the next step is to implement a SQL generator for such specific use cases.

**Comment by odan** [comment]
As a workaround you can use the `$this->execute(...)` method. So for now I close this issue.

**Comment by killua-eu** [comment]
Hey @odan , I'd like to reopen this issue. I have a working example on how to add a generated column properly with phinx - its been supported, only not too obviously documented. Here the code:

```
<?php

use Phinx\Db\Adapter\MysqlAdapter;
use Phinx\Util\Literal;

class Asset extends Phinx\Migration\AbstractMigration
{
    public function change()
    {
        $this->execute('SET unique_checks=0; SET foreign_key_checks=0;');
        $this->table('t_assets_items', [
                'id' => false,
                'primary_key' => ['c_uid'],
                'engine' => 'InnoDB',
                'encoding' => 'utf8mb4',
                'collation' => 'utf8mb4_0900_ai_ci',
                'comment' => 'Assets items',
                'row_format' => 'DYNAMIC',
            ])
            ->addColumn('c_ref1', Literal::from("varchar(255) COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (`c_json`->>'$.uid') VIRTUAL"), [
                'null' => false,
                'comment' => 'Unique row id',
            ])
            ->update();
        $this->execute('SET unique_checks=1; SET foreign_key_checks=1;');
    }
}
```

this does actually the correct thing (--dry-run excerpt)

```
php vendor/bin/phinx migrate -e production --configuration=phinx.yml --dry-run
Phinx by CakePHP - https://phinx.org.

using config file ./phinx.yml
using config parser yml
using migration paths 
 - /srv/varwwwhtml/migrate-test/glued/Core/Install/Migrations
using seed paths 
 - /srv/varwwwhtml/migrate-test/glued/Core/Install/Seeds
using environment production
using adapter mysql
using database glued
ordering by creation time

 == 20201204120000 Asset: migrating
START TRANSACTION;
SET unique_checks=0; SET foreign_key_checks=0;
ALTER TABLE `t_assets_items` ADD `c_ref1` varchar(255) COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (`c_json`->>'$.uid') VIRTUAL NOT NULL COMMENT 'Unique row id';
SET unique_checks=1; SET foreign_key_checks=1;
COMMIT;
INSERT INTO `phinxlog` (`version`, `migration_name`, `start_time`, `end_time`, `breakpoint`) VALUES ('20201204120000', 'Asset', '2020-12-04 10:19:15', '2020-12-04 10:19:15', 0);
 == 20201204120000 Asset: migrated 0.0164s
```

would you mind including supporting this on your side yourself?

**Comment by odan** [comment]
That's nice. I will take a look at it in the next few days.

**Comment by killua-eu** [comment]
Hi Daniel, any progress on this? I'm asking because this issue is closed and could be forgotten easily.

**Comment by odan** [comment]
I have it on my to-do list. At the moment I am very busy.

**Comment by odan** [comment]
Currently I'm trying to add this feature. Your suggested workaround with `Literal::from(...)` is tricky but it works on my dev machine. The "up" direction works so far, but there are some other problems now:

* Changing a generated column would not work with the current logic of the migration generator because a generated column must be dropped and then created to change it. All other fields can be changed directly with phinx, but not this kind of field and with the current logic the generator is internally build.
* Another option would be to generate raw SQL for generated columns, but this would also break a lot of existing internal logic. It would also require adding support for the phinx `up` and `down` method, instead of using the `change` method. So a lot of changes.
* Phinx does not support generated columns. The PR to support it was closed. So I guess it will "never" be supported directly because phinx tries to abstract multiple databases systems.

So you see I've tried it, but this feature needs a lot of more changes under the hood then expected.

**Comment by killua-eu** [comment]
Hey @odan , sorry for my late reaction, I've been really busy. I personally wouldn't mind a partial support for this (meaning at least creating the generated columns). Or would maybe `$table->getColumn('column1')->getType();` help to work with the Literal type differently? I'm aware this would feel hackish to have a specific way how to deal with this, but it feels like an easier way then going raw SQL. Is there anything I could help with to move this on?

**Comment by killua-eu** [comment]
Just a remark: I noticed that dropping the column is required only when changing the `STORED` status of the column. Changing existing normal columns into generated stored columns with 

```
            ->changeColumn('c_vatid', Literal::from("varchar(255) COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (`c_json`->>'$.some[0].thing') STORED"), [
                'null' => true,
```

will work, but trying to change


```
            ->changeColumn('c_vatid', Literal::from("varchar(255) COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (`c_json`->>'$.some[0].thingelse') VIRTUAL"), [
                'null' => true,
```

will fail with 

```
PDOException: SQLSTATE[HY000]: General error: 3106 'Changing the STORED status' is not supported for generated columns. in /srv/varwwwhtml/glued-skeleton/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:194
```

Similarly, changing a VIRTUAL column into a VIRTUAL column with a different json path, it will work just fine . Basicall only changing STORED/VIRTUAL status seems to fail on me.

I'll report this specific issue to phinx, as this would be nicer to deal with upstream, but I'm hoping this could be relatively simple to implement in the generator.

**Comment by odan** [comment]
Phinx is a very good tool, but it also has its limitations.
I just noticed that the requirements of the people and the features of Phinx are getting further and further apart.
Therefore I play with the thought to generate only pure SQL in the next major version. This SQL would then be generated for an up and down method. What do you think about this idea?

**Comment by killua-eu** [comment]
Absolutely makes sense. I've been using phinx mainly because there wasn't any other maintained database migration tool in the php ecosystem and it was still quite a pain to use until your project appeared. 

The things I appreciated about phinx is the change() method while I was still writing migrations manually. Many other things feel unnecessarily abstracted away towards making phinx hard to use in real world.

**Comment by odan** [comment]
I have come to the conclusion that this tool should only offer features that are also supported by Phinx. So as long as Phinx does not support generated columns, this migration generator will not support it. I tried to generate SQL diffs, but that doesn't make sense since Phinx should be responsible for that task. So I'm sorry to close this request, but the work and time involved would be too much for me.

**Comment by zeleznypa** [comment]
Unfortunately, the current version of Phinx (0.15.5) failed on the suggested workaround with the Literal.

https://github.com/cakephp/phinx/issues/2254
