### ISSUE TITLE
Set column type not generated correctly

### ISSUE THREAD

**Issue by joostdebruijn** [odan/phinx-migrations-generator#81]
Columns from the type 'set' are not correctly generated. In the schema.php file the values are discovered, but the property `values` is not added to the column definition migration file. This will cause an error when running the generated migration.

I'm not sure, but this issue may also arise for 'enum' types.

**Comment by odan** [comment]
Hi @joostdebruijn 

The type `ENUM` was already supported. In the next version the type `SET` will also be supported.
