### ISSUE TITLE
schema.php debugging?

### ISSUE THREAD

**Issue by killua-eu** [odan/phinx-migrations-generator#82]
Hi Daniel,

I occasionally notice, that the generate command `./vendor/bin/phinx-migrations generate -e production --name SomeName --overwrite` occasionally tries to recreate an already existing table with an existing migration class, that has its record in schema.php.

I can't really figure out why - is there a way to easily ask the migrate command to print the differences it sees between mysql proper and schema.php, without generating the new migration, or any other way to debug the generate action? 

At first I thought I kept forgetting the overwrite flag which forced the schema.php be left behind, but with progressing time, I think there's something happening that makes the generator try to create a table already present in schema.php (and not update it, if it had changes to itself in the db).

**Comment by odan** [comment]
Usually it is not very common to create a migration from a production database. In most cases it should be a local dev database where you change the schema. The production database is just "the target" to apply the generated migrations. Can you please explain your workflow?
Does the schema.php exist and does it contain the latest schema?
