### ISSUE TITLE
array_key_first() requires PHP 7.3

### ISSUE THREAD

**Issue by MrHHyde** [odan/phinx-migrations-generator#88]
Composer json needs to be updated to require php 7.3

https://github.com/odan/phinx-migrations-generator/blob/091b8930c9e5c820e54d4f65e6b422bf124b2292/composer.json#L16

https://github.com/odan/phinx-migrations-generator/blob/ecb21f9aed310e7276f4f4e3dbaddf76be82369b/src/Migration/Command/GenerateCommand.php#L291

**Comment by odan** [comment]
Thanks for reporting. A polyfill for array_key_first has been added.
