### ISSUE TITLE
I am so support your program, but some bugs still exists.

### ISSUE THREAD

**Issue by gotoin** [odan/phinx-migrations-generator#9]
when execute vendor/bin/phinx migrate
It will be returned

  [PDOException]                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table def  
  inition; there can be only one auto column and it must be defined as a key 

and I confirm my SQL can normal use , please help me to look this 。
thank you

**Comment by gotoin** [comment]
ok, i know now, because phinx automatically assigned id primary key, but i use other field as primary key, so may be have a  solution ? please, thank you.

**Comment by MikeSorokin** [comment]
@gotoin Hello. You could use some magic about this, [Phinx docs](http://docs.phinx.org/en/latest/migrations.html#working-with-tables) says, that you can define custom primary key for table and disable auto creating `id` column. It may look like this:
```
<?php

use Phinx\Migration\AbstractMigration;

class MyNewMigration extends AbstractMigration
{
    /**
     * Migrate Up.
     */
    public function up()
    {
        $table = $this->table('followers', array('id' => false, 'primary_key' => array('user_id', 'follower_id')));
        $table->addColumn('user_id', 'integer')
              ->addColumn('follower_id', 'integer')
              ->addColumn('created', 'datetime')
              ->save();
    }

    /**
     * Migrate Down.
     */
    public function down()
    {

    }
}
```

**Comment by gotoin** [comment]
yes, i know, but i use your phinx-migrations-generator now, could you update this?thank you

**Comment by MikeSorokin** [comment]
@gotoin Could you include some sql dump of your table with this problem and its generated migration?

**Comment by odan** [comment]
If MySQL says "Incorrect table definition; there can be only one auto column and it must be defined as a key" then you just have to add a primary key for the AUTO_INCREMENT field (e.g. id).

**Comment by gotoin** [comment]
@odan i use other field as AUTO_INCREMENT field , so i need phinx-migrations-generator autogeneration like phinx docs says  
$table = $this->table('followers', array('id' => false, 'primary_key' => array('user_id', 'follower_id')));

**Comment by odan** [comment]
Ok i get it. I try to implement this feature in the next days.

**Comment by gotoin** [comment]
thank you very much!
