### ISSUE TITLE
Exporting triggers

### ISSUE THREAD

**Issue by ashuradev** [odan/phinx-migrations-generator#95]
I suggest the idea of ​​exporting triggers.

For example:

```php
$this->execute('CREATE TRIGGER ...');
```

**Comment by odan** [comment]
Good idea. I'm planning to add support for native SQL commands where Phinx does not provide a (full) abstraction. See #80 
I put it on the list.

**Comment by odan** [comment]
I'm sorry. Triggers are not supported by Phinx, so this feature cannot be added to the migrations-generator.
